### ISSUE TITLE
Extract repeated code to functions

### ISSUE THREAD

**Issue by oliverjam** [fac25/Week5-https-project-Abdullah-Lisa#21]
It looks like this code to get an array of genres is mostly repeated twice:

https://github.com/fac25/Week5-https-project-Abdullah-Lisa/blob/423ab443252c884f4d8bc998de0d67c05592455e/script.js#L23-L30

https://github.com/fac25/Week5-https-project-Abdullah-Lisa/blob/423ab443252c884f4d8bc998de0d67c05592455e/script.js#L127-L134

Given it's non-trivial (a few lines including some iteration) it probably makes sense to extract it to a function with a descriptive name. That way you only have to edit/improve the code in one place.

This has the advantage of forcing you to write more general purpose code (these two loops aren't _exactly_ the same). It also can make the surrounding code easier to follow since something like this:

```js
const genres = getGenresFromIds(...);
```

is hopefully a bit clearer than having to stop to parse a loop in your head.

**Comment by flare-s** [comment]
Thank you for the feedback Oli! I think we've managed to do it.
